import { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { ArrowLeft, CalendarIcon, Download, Receipt } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { Breadcrumb } from '@/components/Breadcrumb';
import { DataTable } from '@/components/DataTable';
import { EmptyState } from '@/components/EmptyState';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";


interface MilkSale {
  id: string;
  date: string;
  customer_name: string;
  litres: number;
  amount: number;
  payment_method: string;
  recorded_by: string;
  created_at: string;
}

const SalesReceipts = () => {
  const navigate = useNavigate();
  const [sales, setSales] = useState<MilkSale[]>([]);
  const [loading, setLoading] = useState(true);
  const [dateRange, setDateRange] = useState<{ from: Date; to: Date }>({
    from: new Date(),
    to: new Date()
  });
  const [showFromCalendar, setShowFromCalendar] = useState(false);
  const [showToCalendar, setShowToCalendar] = useState(false);

  useEffect(() => {
    fetchSales();
  }, [dateRange]);

  const fetchSales = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('milk_sales')
        .select('*')
        .gte('date', format(dateRange.from, 'yyyy-MM-dd'))
        .lte('date', format(dateRange.to, 'yyyy-MM-dd'))
        .order('date', { ascending: false })
        .order('created_at', { ascending: false });

      if (error) throw error;
      setSales(data || []);
    } catch (error: any) {
      console.error('Error fetching sales:', error);
      toast.error('Failed to load sales records');
    } finally {
      setLoading(false);
    }
  };

  const stats = useMemo(() => {
    const totalSales = sales.reduce((sum, sale) => sum + parseFloat(sale.amount.toString()), 0);
    const totalLitres = sales.reduce((sum, sale) => sum + parseFloat(sale.litres.toString()), 0);
    const mpesaSales = sales.filter(s => s.payment_method === 'mpesa').reduce((sum, sale) => sum + parseFloat(sale.amount.toString()), 0);
    const cashSales = sales.filter(s => s.payment_method === 'cash').reduce((sum, sale) => sum + parseFloat(sale.amount.toString()), 0);
    const bankSales = sales.filter(s => s.payment_method === 'bank').reduce((sum, sale) => sum + parseFloat(sale.amount.toString()), 0);
    const creditSales = sales.filter(s => s.payment_method === 'credit').reduce((sum, sale) => sum + parseFloat(sale.amount.toString()), 0);

    return {
      total: totalSales,
      litres: totalLitres,
      mpesa: mpesaSales,
      cash: cashSales,
      bank: bankSales,
      credit: creditSales,
      count: sales.length
    };
  }, [sales]);


const downloadReceipt = () => {
  if (!sales || sales.length === 0) {
    toast.error("No records to download");
    return;
  }

  const doc = new jsPDF();

  // Title
  doc.setFontSize(16);
  doc.text("TRYDT Farmstead - Milk Sales Report", 14, 20);

  // Report details
  doc.setFontSize(11);
  doc.text(`Report Period: ${format(dateRange.from, "PPP")} - ${format(dateRange.to, "PPP")}`, 14, 30);
  doc.text(`Generated On: ${format(new Date(), "PPP")}`, 14, 37);

  // Summary Table
  autoTable(doc, {
    startY: 45,
    head: [["Metric", "Value"]],
    body: [
      ["Total Litres Sold", `${stats.litres.toFixed(1)} L`],
      ["Total Sales", `KES ${stats.total.toFixed(2)}`],
      ["M-Pesa Payments", `KES ${stats.mpesa.toFixed(2)}`],
      ["Cash Payments", `KES ${stats.cash.toFixed(2)}`],
      ["Bank Payments", `KES ${stats.bank.toFixed(2)}`],
      ["Credit Payments", `KES ${stats.credit.toFixed(2)}`],
      ["Transactions", stats.count.toString()],
    ],
    headStyles: { fillColor: [0, 100, 0] }, // green
  });

  // Detailed Sales Table
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [["Date", "Customer", "Litres", "Amount (KES)", "Payment", "Recorded By"]],
    body: sales.map((s) => [
      format(new Date(s.date), "PP"),
      s.customer_name,
      `${parseFloat(s.litres.toString()).toFixed(1)} L`,
      `KES ${parseFloat(s.amount.toString()).toFixed(2)}`,
      s.payment_method.toUpperCase(),
      s.recorded_by,
    ]),
    headStyles: { fillColor: [101, 67, 33] }, // brown tone
    alternateRowStyles: { fillColor: [240, 240, 240] },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.text(
    "Generated by TRYDT Farmstead System | © 2025",
    14,
    pageHeight - 10
  );

  doc.save(
    `milk_sales_${format(dateRange.from, "yyyy-MM-dd")}_to_${format(dateRange.to, "yyyy-MM-dd")}.pdf`
  );

  toast.success("Receipt downloaded successfully!");
};



  const columns = [
    { key: 'date', label: 'Date', render: (item: MilkSale) => format(new Date(item.date), 'PP') },
    { key: 'customer_name', label: 'Customer' },
    { key: 'litres', label: 'Litres', render: (item: MilkSale) => `${parseFloat(item.litres.toString()).toFixed(1)} L` },
    { key: 'amount', label: 'Amount', render: (item: MilkSale) => `KES ${parseFloat(item.amount.toString()).toFixed(2)}` },
    { key: 'payment_method', label: 'Payment', render: (item: MilkSale) => (
      <span className={cn(
        "px-2 py-1 rounded-full text-xs font-medium",
        item.payment_method === 'mpesa' && "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
        item.payment_method === 'cash' && "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
        item.payment_method === 'bank' && "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
        item.payment_method === 'credit' && "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200"
      )}>
        {item.payment_method.toUpperCase()}
      </span>
    )},
    { key: 'recorded_by', label: 'Recorded By' }
  ];

  return (
    <div className="min-h-screen bg-background p-4 pb-8">
      <div className="max-w-6xl mx-auto">
        <div className="mb-6 pt-6">
          <Button
            onClick={() => navigate('/')}
            variant="ghost"
            size="sm"
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
          <Breadcrumb />
        </div>

        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <Receipt className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-2xl font-bold text-foreground">Sales Receipts</h1>
              <p className="text-muted-foreground">View and download payment records</p>
            </div>
          </div>
          <Button onClick={downloadReceipt} disabled={sales.length === 0}>
            <Download className="h-4 w-4 mr-2" />
            Download Receipt
          </Button>
        </div>

        <Card className="p-6 mb-6">
          <div className="flex flex-col md:flex-row gap-4 mb-6">
            <div className="flex-1">
              <label className="text-sm font-medium mb-2 block">From Date</label>
              <Popover open={showFromCalendar} onOpenChange={setShowFromCalendar}>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full justify-start">
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {format(dateRange.from, 'PPP')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={dateRange.from}
                    onSelect={(date) => {
                      if (date) {
                        setDateRange({ ...dateRange, from: date });
                        setShowFromCalendar(false);
                      }
                    }}
                    initialFocus
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
            <div className="flex-1">
              <label className="text-sm font-medium mb-2 block">To Date</label>
              <Popover open={showToCalendar} onOpenChange={setShowToCalendar}>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full justify-start">
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {format(dateRange.to, 'PPP')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={dateRange.to}
                    onSelect={(date) => {
                      if (date) {
                        setDateRange({ ...dateRange, to: date });
                        setShowToCalendar(false);
                      }
                    }}
                    disabled={(date) => date < dateRange.from}
                    initialFocus
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-6 gap-4">
            <div className="bg-primary/10 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Total Litres</p>
              <p className="text-2xl font-bold text-foreground">{stats.litres.toFixed(1)} L</p>
            </div>
            <div className="bg-accent/10 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Total Sales</p>
              <p className="text-2xl font-bold text-foreground">KES {stats.total.toFixed(2)}</p>
            </div>
            <div className="bg-green-100 dark:bg-green-900/30 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">M-Pesa</p>
              <p className="text-xl font-bold text-foreground">KES {stats.mpesa.toFixed(2)}</p>
            </div>
            <div className="bg-blue-100 dark:bg-blue-900/30 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Cash</p>
              <p className="text-xl font-bold text-foreground">KES {stats.cash.toFixed(2)}</p>
            </div>
            <div className="bg-yellow-100 dark:bg-yellow-900/30 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Bank</p>
              <p className="text-xl font-bold text-foreground">KES {stats.bank.toFixed(2)}</p>
            </div>
            <div className="bg-orange-100 dark:bg-orange-900/30 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Credit</p>
              <p className="text-xl font-bold text-foreground">KES {stats.credit.toFixed(2)}</p>
            </div>
            <div className="bg-secondary/10 p-4 rounded-lg">
              <p className="text-sm text-muted-foreground">Transactions</p>
              <p className="text-2xl font-bold text-foreground">{stats.count}</p>
            </div>
          </div>
        </Card>

        {loading ? (
          <div className="text-center py-12">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
            <p className="mt-4 text-muted-foreground">Loading sales records...</p>
          </div>
        ) : sales.length === 0 ? (
          <EmptyState
            title="No sales records found"
            description="Try selecting a different date range or record a new sale"
          />
        ) : (
          <Card className="p-6">
            <DataTable columns={columns} data={sales} />
          </Card>
        )}
      </div>
    </div>
  );
};

export default SalesReceipts;
